#!/usr/bin/env python3
"""Space Wargame Engine — CLI Launcher"""
import asyncio
from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel

console = Console()


def _select_scenario() -> Path:
    scenario_dir = Path(__file__).resolve().parent / "scenarios"
    scenarios = list(scenario_dir.glob("*.yaml"))
    if not scenarios:
        console.print("[red]No scenario files found in scenarios/[/red]")
        raise SystemExit(1)
    console.print("[bold]Available scenarios:[/bold]")
    for i, s in enumerate(scenarios):
        console.print(f"  {i+1}. {s.stem}")
    try:
        choice = int(Prompt.ask("Select scenario", default="1")) - 1
    except ValueError:
        console.print("[red]Invalid selection — enter a number.[/red]")
        raise SystemExit(1)
    if not (0 <= choice < len(scenarios)):
        console.print(f"[red]Choice must be between 1 and {len(scenarios)}.[/red]")
        raise SystemExit(1)
    return scenarios[choice]


def _configure_agents(scenario, persona_dir: Path = Path("personas")) -> dict:
    from agents.rule_based import MahanianAgent
    from agents.ai_commander import AICommanderAgent
    from agents.human import HumanAgent
    from personas.builder import load_archetype
    import io
    from ruamel.yaml import YAML

    agents = {}
    for faction in scenario.factions:
        console.print(f"\n[bold cyan]{faction.name}[/bold cyan] ({faction.archetype})")
        console.print(f"  Default agent type: {faction.agent_type}")
        valid_types = ["human", "human+advisor", "ai_commander", "rule_based"]
        if faction.agent_type not in valid_types:
            console.print(f"  [yellow]Warning: unknown agent_type '{faction.agent_type}', defaulting to rule_based[/yellow]")
        agent_type = Prompt.ask(
            "  Agent type",
            choices=valid_types,
            default=faction.agent_type if faction.agent_type in valid_types else "rule_based",
        )

        if agent_type == "rule_based":
            agent = MahanianAgent()
        elif agent_type in ("human", "human+advisor"):
            advisor = None
            if agent_type == "human+advisor":
                yaml = YAML()
                buf = io.StringIO()
                archetype_data = load_archetype(faction.archetype)
                yaml.dump(archetype_data, buf)
                advisor = AICommanderAgent(persona_yaml=buf.getvalue())
                advisor.initialize(faction)
            agent = HumanAgent(advisor=advisor)
        else:  # ai_commander
            yaml = YAML()
            buf = io.StringIO()
            custom_path = persona_dir / "custom" / f"{faction.faction_id}.yaml"
            if custom_path.exists():
                archetype_data = yaml.load(custom_path)
            else:
                archetype_data = load_archetype(faction.archetype)
            yaml.dump(archetype_data, buf)
            agent = AICommanderAgent(persona_yaml=buf.getvalue())

        agent.initialize(faction)
        agents[faction.faction_id] = agent
    return agents


def _print_game_overview():
    from rich.table import Table
    console.print(Panel(
        "[bold]SPACE WARGAME ENGINE[/bold]\n"
        "Strategic AI competition for space dominance\n\n"
        "[dim]Theoretical framework: Ziarnick / Carlson (wine dark sea)[/dim]",
        border_style="cyan"
    ))

    console.print(Panel(
        "[bold]HOW TO PLAY[/bold]\n\n"
        "You command a space faction competing for [cyan]orbital dominance[/cyan] — the share of "
        "total orbital nodes your coalition controls. The faction (or coalition) that controls a "
        "sufficient fraction of the orbital commons wins.\n\n"
        "[bold yellow]Each turn has three phases:[/bold yellow]",
        border_style="dim"
    ))

    phases = Table(show_header=True, header_style="bold yellow", box=None, padding=(0, 2))
    phases.add_column("Phase")
    phases.add_column("What you decide")
    phases.add_column("Key concept")
    phases.add_row(
        "[bold]1 · INVEST[/bold]",
        "Allocate your budget across 8 categories",
        "Constellation nodes score orbital dominance; covert/R&D compound over time",
    )
    phases.add_row(
        "[bold]2 · OPERATIONS[/bold]",
        "Choose one operational action",
        "Gray-zone and task_assets are low-risk; retaliation raises board tension",
    )
    phases.add_row(
        "[bold]3 · RESPONSE[/bold]",
        "React to crisis events generated by the referee",
        "Escalating increases tension and unlocks harder actions — but costs coalition trust",
    )
    console.print(phases)

    console.print(Panel(
        "[bold]Key mechanics[/bold]\n\n"
        "[cyan]Space Domain Awareness (SDA)[/cyan]  Your sensor investment determines how much "
        "of the adversary's order of battle you can see. Low SDA = fog of war.\n\n"
        "[cyan]Deferred returns[/cyan]  R&D pays off in 3 turns; Education in 6. "
        "Invest early or you'll be buying capability you can't use.\n\n"
        "[cyan]Coalition loyalty[/cyan]  You win or lose as a coalition, not alone. "
        "Defection is possible — AI actors with low loyalty may not coordinate.\n\n"
        "[cyan]Crisis events[/cyan]  The referee generates 0–2 events per turn based on board tension. "
        "How you respond shapes the narrative and the next turn's options.",
        border_style="dim"
    ))
    console.print()


async def main():
    _print_game_overview()

    scenario_path = _select_scenario()

    from scenarios.loader import load_scenario
    scenario = load_scenario(scenario_path)
    console.print(f"\nLoaded: [bold]{scenario.name}[/bold] ({scenario.turns} turns)")
    console.print(f"  {scenario.description}")

    agents = _configure_agents(scenario)

    from output.audit import AuditTrail
    from output.strategy_lib import StrategyLibrary
    from engine.referee import GameReferee

    Path("output").mkdir(exist_ok=True)
    audit = AuditTrail("output/game_audit.db")
    await audit.initialize()

    try:
        referee = GameReferee(scenario=scenario, agents=agents, audit=audit)

        console.print("\n[bold green]Starting game...[/bold green]\n")
        result = await referee.run()

        console.print("\n" + "="*60)
        if result.winner_coalition:
            console.print(f"[bold green]WINNER: {result.winner_coalition} coalition[/bold green]")
        else:
            console.print("[yellow]DRAW — no faction achieved hegemony[/yellow]")
        console.print(f"Turns completed: {result.turns_completed}")
        for fid, outcome in result.faction_outcomes.items():
            color = "green" if outcome == "won" else "red"
            console.print(f"  [{color}]{fid}: {outcome}[/{color}]")

        strategy_lib = StrategyLibrary()
        strategy_lib.record_run(scenario, result)

        # Collect and log token usage from all AI agents (commanders + advisors)
        from agents.ai_commander import AICommanderAgent
        from rich.table import Table as RichTable

        token_rows = []
        for fid, agent in agents.items():
            if isinstance(agent, AICommanderAgent):
                await audit.write_token_usage(fid, "commander", agent._model, agent.token_totals)
                token_rows.append((fid, "commander", agent._model, agent.token_totals))
            if hasattr(agent, "_advisor") and isinstance(agent._advisor, AICommanderAgent):
                await audit.write_token_usage(fid, "advisor", agent._advisor._model, agent._advisor.token_totals)
                token_rows.append((fid, "advisor", agent._advisor._model, agent._advisor.token_totals))

        if token_rows:
            _COSTS = {
                "claude-sonnet-4-6": {"input": 3.0, "output": 15.0, "cache_read": 0.30, "cache_creation": 3.75},
                "claude-opus-4-7":   {"input": 15.0, "output": 75.0, "cache_read": 1.50, "cache_creation": 18.75},
            }

            def _estimate_cost(model: str, totals: dict) -> float:
                rates = _COSTS.get(model, _COSTS["claude-sonnet-4-6"])
                return (
                    totals["input_tokens"] * rates["input"] / 1_000_000 +
                    totals["output_tokens"] * rates["output"] / 1_000_000 +
                    totals["cache_read_tokens"] * rates["cache_read"] / 1_000_000 +
                    totals["cache_creation_tokens"] * rates["cache_creation"] / 1_000_000
                )

            console.print("\n[bold]TOKEN USAGE[/bold]")
            tok_table = RichTable(show_header=True, header_style="bold", box=None, padding=(0, 2))
            tok_table.add_column("Faction")
            tok_table.add_column("Role")
            tok_table.add_column("Model", style="dim")
            tok_table.add_column("Input", justify="right")
            tok_table.add_column("Output", justify="right")
            tok_table.add_column("Cache-R", justify="right")
            tok_table.add_column("Cache-W", justify="right")
            tok_table.add_column("Est. Cost", justify="right")
            total_cost = 0.0
            for fid, role, model, totals in token_rows:
                cost = _estimate_cost(model, totals)
                total_cost += cost
                tok_table.add_row(
                    fid, role, model,
                    f"{totals['input_tokens']:,}",
                    f"{totals['output_tokens']:,}",
                    f"{totals['cache_read_tokens']:,}",
                    f"{totals['cache_creation_tokens']:,}",
                    f"${cost:.4f}",
                )
            console.print(tok_table)
            console.print(f"  [dim]Total estimated cost: ${total_cost:.4f}[/dim]")

        if Confirm.ask("\nGenerate after-action report?", default=True):
            from output.aar import AfterActionReportGenerator
            console.print("[dim]Generating AAR via Claude Opus...[/dim]")
            aar_gen = AfterActionReportGenerator()
            aar_text = await aar_gen.generate(audit=audit, scenario_name=scenario.name)
            aar_path = Path("output") / f"aar_{scenario.name.replace(' ', '_').lower()}.md"
            aar_path.write_text(aar_text)
            console.print(f"[green]AAR saved to {aar_path}[/green]")
            console.print("\n[bold]AFTER-ACTION REPORT EXCERPT:[/bold]")
            console.print(aar_text[:1000] + "...")
    finally:
        await audit.close()


if __name__ == "__main__":
    asyncio.run(main())
